[package]
name = "eg-term"
version = "0.1.0"
edition = "2021"

[dependencies]
font8x8 = { version = "0.3.1", default-features = false }
minifb = { version = "0.24.0", default-features = false, features = ["x11"] }
